# Generated by Django 3.2.3 on 2021-11-09 09:43

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
